### ISSUE TITLE
Kinguin-eCommerce-API suggestions from "cdkeysell.ir" developers team

### ISSUE THREAD

**Issue by mrez-ir** [kinguinltdhk/Kinguin-eCommerce-API#1]
Kinguin-eCommerce-API suggestions from "cdkeysell.ir" developers team

1- Merchants and Offers are not included yet: [Improvement/Extending]
This feature is very useful for automating ordering system because the system should be able to select best price from offers of trustworthy merchants and not only low price offers which could be risky or scam.

2- Price Conversion: [Compatibility/Accuracy/Synchronization]
In current API system we could only get product prices in EURO. It's a good idea if there could be a header on request which defines our preferred pricing unit for example getting prices in USD rather than EURO. This conversion can also be done in client side(ex. our site) but it can be very inaccurate if EURO and USD values and balances changed on kinguin or in the world every day.

3- Requesting List of Product Info From Multiple Product ID's: [Bandwidth/Speed/Less-Requests/Optimization/Synchronization]
Currently API system is only able to return only one product from its id otherwise if we want list of products we can filter products based on attributes. But sometimes we need synchronize information of some exact product ids. In this case we should send and receive individual requests for each product_id which cause the system slower and costs more bandwidth and process.

4- Filtering Product Attributes (only get attributes that we want not whole product attributes): [Bandwidth/Speed/Optimization/Minimized_Responses]
Imagine we're updating product prices on our local shop. We don't need any extra information from extra product attributes like product description, images, etc. These attributes should be excluded and filterable from request data. Imagine currently when we're applying price update to our kinguin products in local shop; we should send separate request for each product and each response have full information of that product which is not going to be used. This is totally waste of bandwidth, process and time on both sides.

*** Our suggestion for making most of above problems solved in single easy step ***
Generating a new function for kinguins API can make most of above problems solved. You can generate a function to accept json POST requests with these kind of json data:
1- an array of product kinguinIds to be processed (ex. `array(34523,5643,23455,5321,54540,57734)`)
2- a selective array of product attributes to be returned at response (for example `array('kinguinId','name','price','stock')`) orelse an array of product attributes to be excluded in json response (for example `array('description','languages','images','extra_fields')`)
3- preferred currency (This can also be moved to header part. Maybe not required here on that case)
4- an array of product pricing preferences for selecting best suited offer [for example input `array(minimum_completed_orders=>100,minimum_rate_counts=>1,minimum_rate_percent=>98)`]
5- an array of extra product filters (for example do not return information of products with non-changed prices since a time. example array(`last_price_update_time=>'some-date')`)

**Comment by Ghost-DL** [comment]
Great points. Have you been able to get the Postback working?

**Comment by lkuziola** [comment]
Hi,
Thank you for your valuable and interesting comments.
We added points like 3 and 4 to our backlog.
We will inform you when we it will be released.
Points like 1 and 2 requires a thorough business analysis, so we are not immediately assessing whether their implementation will be possible.

**Comment by lkuziola** [comment]
Hi,
The `kinguinId` field has been extended to set multiple products ids (comma separated).
