### ISSUE TITLE
Suggestion: api url for retrieving regions/genres/platforms

### ISSUE THREAD

**Issue by Desomph** [kinguinltdhk/Kinguin-eCommerce-API#11]
So, currently the only way we can know which regions and genres are available is by having it in some kind of config or database like this:
```JS
const Genres = [
  "Action",
  "Adventure",
  "Anime",
  ...
];

const Regions = [
  {
    "id": 1,
    "name": "Europe"
  },
  {
    "id": 2,
    "name": "United States"
  },
  {
    "id": 3,
    "name": "Region free"
  },
  ...
];
```

But it would be awesome if you could create accessible API backend that can list us available regions and genres so that we don't have to check for potential changes by reading the Readme's and instead of occasional querying of your backend.

Edit: It would also be good to get a list of platforms, because currently this is not an option.

**Comment by lkuziola** [comment]
Hi,
It is possible.
We've added that to our backlog.

Thanks ;)
