### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by dlaslo** [kinguinltdhk/Kinguin-eCommerce-API#12]
This issue/question is related to the price returned by catalog calls. 

I have seen this as a suggestion in ticket (https://github.com/kinguinltdhk/Kinguin-eCommerce-API/issues/1) and I am thinking that there are no steps further in implementing this feature. We tried from different IP (USA for instance) to get the price in $ with no success, the currency remains EUR. 
Could not find any reliable info about this so we are assuming that the expected behavior is to get the price in EUR. 

Since we still need to have it in $, can we rely on https://api.kinguin.net/v1/currency/rates/USD to get the conversion rate. With this conversion rate the prices match the ones displayed on the website. 
Is this a reliable conversion or it is just a happy accident for the few products we checked? 

Thank you

**Comment by karolmalinowski** [comment]
Currently there are no plans for other currencies than EUR so you can use mentioned currency rates endpoint to calculate exchange rate.
