### ISSUE TITLE
Anti dos protection?

### ISSUE THREAD

**Issue by pijussau** [kinguinltdhk/Kinguin-eCommerce-API#14]
Why are you running anti dos protection on the API? It makes no sense. I am not able to fetch your products or update my store prices because your Anti dos protection have blocked my store IP.

**Comment by KamilKinguinAPI** [comment]
Hi @pijussau , 

I understand that our protection strategy could be troublesome for you. However, it is necessary from our point of view. Please write me an email with your IP we will unblock your IP.

Best Regards, 
Kamil
kg@kinguin.io
