### ISSUE TITLE
Sorting by popularity

### ISSUE THREAD

**Issue by bsrnmhmt** [kinguinltdhk/Kinguin-eCommerce-API#2]
Products list can be sorted by name, id, price but it would be nice if the list could be sorted by popularity.

**Comment by lkuziola** [comment]
Hi,
We do not provide popularity information.
If it is satisfactory for you, we can consider the sorting by 'steamScore` or `metacriticScore` fields.

**Comment by bsrnmhmt** [comment]
Ok. We don't need sorting by 'steamScore`or`metacriticScore`. Thanks.
