### ISSUE TITLE
Provide official price

### ISSUE THREAD

**Issue by atmar** [kinguinltdhk/Kinguin-eCommerce-API#3]
Hello,

It would be nice to have the official price in the product data aswell to show how much discount we offer compared to the official price

**Comment by KamilKinguinAPI** [comment]
Dear @atmar 

Thank you for interest and I am very sorry for so long response. 

Great thank you. Your contribution and feedback are very important to us. 
Unfortunately, we don’t have plans to release this feature in the upcoming future. However, we have added your idea to our backlog. 

Regards,
