### ISSUE TITLE
Dispatch endpoint usage 

### ISSUE THREAD

**Issue by DavidGOrtega** [kinguinltdhk/Kinguin-eCommerce-API#30]
:wave: Hi! 
What is dispatch and when your it be used?
Right now seems that I can get the keys without calling dispatch, having automatically  the order  a dispatch id.

@seniorquico? 🙏

**Comment by seniorquico** [comment]
The Kinguin team told me that if you register & use webhooks, then they will automatically dispatch the orders and you don't need to call that API endpoint. Works that way for us, and it's much easier. Just create the order, wait for the webhook call, and then get the key.

**Comment by DavidGOrtega** [comment]
@seniorquico 🙏 
> Works that way for us, and it's much easier. Just create the order, wait for the webhook call, and then get the key.

Im doing a small polling instead as they also recommend looking at status. Right now Im just using webhooks to update the product for obvious reasons.

**Comment by DavidGOrtega** [comment]
Closing as it appears that the dispatch is not needed
