### ISSUE TITLE
Products object doesnt return totalQuantity

### ISSUE THREAD

**Issue by iGavrilo** [kinguinltdhk/Kinguin-eCommerce-API#31]
Hey, 

I'd like to ask if is it possible get total totalQuantity of product maybe with prices ? If i try GET https://gateway.kinguin.net/esa/api/v1/products it will return only "qty": 116, with cheapestOfferId.

Thanks

**Comment by lbphp** [comment]
Have you tried the API v2? The endpoint you used is the old v1

I have also a question for you. How to actually make your customer pay for a product/order?

The API docs on the Kinguin's github only explain how to create an order, but not how to actually ask the customer for the credit card info and complete the payment.

It just says that to dispatch an order you have to use Webhooks. But those are just to receive notification when an order status changes, not to make the actual payment

Thanks

**Comment by iGavrilo** [comment]
@lbphp I think so payment its on your side ... Stripe for example ...
