### ISSUE TITLE
Unknown inaccessible API

### ISSUE THREAD

**Issue by Pondake** [kinguinltdhk/Kinguin-eCommerce-API#9]
https://api.kinguin.net/docs/#!/catalog/

This has been giving to me by mail. It sometimes refers to the eCommerce API. At the top of the page it says "Public API", however I need authentication if I want to perform:
"https://api.kinguin.net/v2/sales/orders"

I can't find documentation about this page anywhere.

**Comment by KamilKinguinAPI** [comment]
Dear @Pondake ,

Thank you for interest and I am very sorry for so long response. 

The API describes https://api.kinguin.net/docs/#!/catalog/ isn’t related with our API https://api2.kinguin.net/integration. We are very sorry for misleading you. 
Unfortunately, we cannot provide you with such documentation. If there is a relevant cause you want to use is, please elaborate your idea and send to me on email integration@kinguin.net. I will forward your message to the proper department. 

Regards,
